[window]
decorations="full"
decorations_theme_variant = "Light" # "Dark"
opacity=0.8
startup_mode="Fullscreen"

[general]
import = [
  #"~/.config/alacritty/themes/gruvbox_light.toml"
  "~/.config/alacritty/themes/catppuccin_latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]
live_config_reload = true

[font]
normal.family = "OverpassM Nerd Font Propo"
bold.family = "OverpassM Nerd Font Propo"
italic.family = "OverpassM Nerd Font Propo"
bold_italic.family = "OverpassM Nerd Font Propo"
size=14

#[font.normal]
#family="Overpass Mono"

[terminal.shell]
program = "tmux"
